# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'aobaApp-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for aobaApp-iOS
    pod 'Firebase/Core'
    pod 'Firebase/Storage'
  
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
end


